apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ingress-nginx-controller
spec:
  minReplicas: 1
  maxReplicas: 8
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ingress-nginx-controller
  targetCPUUtilizationPercentage: 80
