apiVersion: v1
data:
  alertmanager.yaml: IyBleHRlcm5hbCBhbGVydG1hbmFnZXIgeWFtbA0KZ2xvYmFsOg0KICByZXNvbHZlX3RpbWVvdXQ6IDEwbQ0Kcm91dGU6DQogIGdyb3VwX2J5OiBbImpvYiJdDQogIGdyb3VwX3dhaXQ6IDMwcw0KICBncm91cF9pbnRlcnZhbDogNW0NCiAgcmVwZWF0X2ludGVydmFsOiAxMmgNCiAgcmVjZWl2ZXI6ICJudWxsIg0KICByb3V0ZXM6DQogICAgLSBtYXRjaDoNCiAgICAgICAgYWxlcnRuYW1lOiBXYXRjaGRvZw0KICAgICAgcmVjZWl2ZXI6ICJudWxsIg0KcmVjZWl2ZXJzOg0KICAtIG5hbWU6ICJudWxsIg0K
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
