resources:
- 00namespace-namespace.yaml
- 0prometheus-operator-0alertmanagerCustomResourceDefinition.yaml
- 0prometheus-operator-0podmonitorCustomResourceDefinition.yaml
- 0prometheus-operator-0prometheusCustomResourceDefinition.yaml
- 0prometheus-operator-0prometheusruleCustomResourceDefinition.yaml
- 0prometheus-operator-0servicemonitorCustomResourceDefinition.yaml
- 0prometheus-operator-0thanosrulerCustomResourceDefinition.yaml
- 0prometheus-operator-clusterRole.yaml
- 0prometheus-operator-clusterRoleBinding.yaml
- 0prometheus-operator-deployment.yaml
- 0prometheus-operator-service.yaml
- 0prometheus-operator-serviceAccount.yaml
- 0prometheus-operator-serviceMonitor.yaml
- alertmanager-alertmanager.yaml
- alertmanager-secret.yaml
- alertmanager-service.yaml
- alertmanager-serviceAccount.yaml
- alertmanager-serviceMonitor.yaml
- grafana-config.yaml
- grafana-dashboardDatasources.yaml
- grafana-dashboardDefinitions.yaml
- grafana-dashboardSources.yaml
- grafana-deployment.yaml
- grafana-service.yaml
- grafana-serviceAccount.yaml
- grafana-serviceMonitor.yaml
- kube-state-metrics-clusterRole.yaml
- kube-state-metrics-clusterRoleBinding.yaml
- kube-state-metrics-deployment.yaml
- kube-state-metrics-service.yaml
- kube-state-metrics-serviceAccount.yaml
- kube-state-metrics-serviceMonitor.yaml
- node-exporter-clusterRole.yaml
- node-exporter-clusterRoleBinding.yaml
- node-exporter-daemonset.yaml
- node-exporter-service.yaml
- node-exporter-serviceAccount.yaml
- node-exporter-serviceMonitor.yaml
- prometheus-clusterRole.yaml
- prometheus-clusterRoleBinding.yaml
- prometheus-prometheus.yaml
- prometheus-roleBindingConfig.yaml
- prometheus-roleBindingSpecificNamespaces.yaml
- prometheus-roleConfig.yaml
- prometheus-roleSpecificNamespaces.yaml
- prometheus-rules.yaml
- prometheus-service.yaml
- prometheus-serviceAccount.yaml
- prometheus-serviceMonitor.yaml
- prometheus-serviceMonitorApiserver.yaml
- prometheus-serviceMonitorCoreDNS.yaml
- prometheus-serviceMonitorKubelet.yaml
