apiVersion: v1
kind: Service
metadata:
  name: flux
  namespace: flux
  labels:
    name: flux
spec:
  selector:
    name: flux
  ports:
    - name: monitor
      port: 3031
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux
  namespace: flux
spec:
  selector:
    matchLabels:
      name: flux
  endpoints:
    - port: monitor
