apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: default
spec:
  chart:
    releaseName: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 2.13.0
  values:
    controller:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
