resources:
  - ../base/hello-world
  - ../base/podinfo
  - ../overlays/ingress-nginx
  - ../overlays/helm-operator

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ingress-nginx-controller
    spec:
      template:
        spec:
          containers:
            - name: controller
              resources:
                requests:
                  cpu: 250m
