apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: default
spec:
  chart:
    releaseName: prometheus
    repository: https://kubernetes-charts.storage.googleapis.com
    name: prometheus-operator
    version: 9.3.1
  values:
    alertmanager:
      enabled: false
