apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: flux
spec:
  template:
    spec:
      containers:
        - name: flux
          args:
            - --manifest-generation=true
            - --memcached-hostname=memcached.flux
            - --memcached-service=
            - --ssh-keygen-dir=/var/fluxd/keygen
            - --git-branch=master
            - --git-path=cluster
            - --git-user=sati290
            - --git-email=sati290@users.noreply.github.com
            - --git-url=git@github.com:sati290/kube-test
            - --sync-garbage-collection
